language: java
sudo: false
jdk:
  - openjdk11
env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2

addons:
  sonarcloud:
    organization: pdxfinder
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=pdxfinder-validator -Dsonar.login="2gkNUyjpGwIWPauQqSpWoKFcJW9/4b/F6Zd4TgcdQ787MLIoc/p5T6HBt9Yh3ERecvLTBII0GqBx1VkGg5fKf5KJ7f09Ns81AfnqZZ8Sc3GAAjqk3tm0pgISfJjCHwxRgxK6SyU1Zyl/yiO43R8hU4mnsmqvZWN/LtdZYQsI3KQ+vnGwLdSQ9u5iqnWGT0vkWqQTOj5p2GBgizY67Y/xtdA0TACUcxxZXJZurKaxJX0yzqTY/zpqbEL11Y9XYHLIsUndTIgstAEl1WWDE90dt33S7Xc2W8lr/9E9HFdOCZPF3nn9yjPsDHlO5USVJrO25OQo8TRC0zQT5P9tsrzsT4f1VemBE92DPEiyKZ6u0BJLAeeyQKLfR7f46Wb7sh8Qg5pB+SS/3JiZtUu6Qt5Tw+CeyR9wNn7Q2NLVWheQQNDKCdS0s+N8E2ZgDYZomYo0In+p9h4wq1uJgaBFK/d09RrjWZ8qjfhYTsp6S7El1r63lDVWAEQZkMWTHWhGTKiG3nlGtQTQr5e754OB006YtRL5IArYOaf+8pbbzpaY1Erw3VCPIFf3t/q2x5pAqN71H6NEHxUbcL5kZK+WPoubyXjqtk/7H63I9qlcXqmbR+2SsCOinjjP9ofEvyrY4otDb5Dka9WZN2Yo4iimhn6BcvBqPKadWAAZb01jZfSEvvM="
