apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdx-validator-dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pdx-validator-dev
    spec:
      containers:
        - name: pdx-validator-dev
          image: 'pdxfinder/pdx-validator:dev_image'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pdx-validator-dev-service
  labels:
    name: pdx-validator-dev-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30931
  selector:
    app: pdx-validator-dev
  type: NodePort

